# Generated by Django 5.1.4 on 2025-01-10 21:22

import cfa_simulation.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('include_inflation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                (
                    'event',
                    models.CharField(
                        choices=[
                            (cfa_simulation.models.ValidEvents['monthly_income'], 'monthly_income'),
                            (cfa_simulation.models.ValidEvents['house_buy'], 'house_buy'),
                            (cfa_simulation.models.ValidEvents['bonds_buy'], 'bonds_buy'),
                            (cfa_simulation.models.ValidEvents['etf_buy'], 'etf_buy'),
                        ],
                        max_length=255,
                    ),
                ),
                ('value', models.FloatField()),
                (
                    'simulation',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfa_simulation.simulation'),
                ),
            ],
        ),
    ]
